library(polybreedR)
library(tidyverse)
library(dplyr)
library(tidyr)
setwd("~/Documents/usda potato breeding/genotyping")

#read in the phenotype/pedigree data from crkn project 
#write.csv(data2324, "data2324.csv", row.names = FALSE) #I am using a dataframe generated by Dr. Feldman's code to ensure accuracy 
data2324 <- read.csv("data2324.csv")

#make a pedigree file for polybreedR
ped <- as.data.frame(unique(data2324$Clone))
ped$father<- data2324$Male[match(unique(data2324$Clone), data2324$Clone)]
ped$mother<- data2324$Female[match(unique(data2324$Clone), data2324$Clone)]
names(ped)[1] <- "id"

#drop entries from ped file where there is no match for the id with the genotype data (you need to load genotype data before running this)
ped <- ped[ped$id %in% colnames(geno.parents), ]
rownames(ped) <- NULL
nrow(ped)
#pedfile <- pedfile[pedfile$father != "CONTROL", ]


#read in snp dose data (already in discrete 0-4 values)
genotypes <- read.csv("~/Documents/usda potato breeding/data_analysis/genotypes/CoanaysisReport-DP26-11898/DP26-11898_Allele_Dose_Report.csv")
#reformat the snp data so I can use it with polybreedR
genotypes <- genotypes[, !names(genotypes) %in% c("X..1","X..2","X..3","X..4")] #remove some columns 
names(genotypes) <- as.character(unlist(genotypes[6, ])) #remove extranous rows so that its lke the viginette example
genotypes <- genotypes[-(1:6), ]
genotypes <- genotypes[-1, ]
rownames(genotypes) <- NULL
names(genotypes)[names(genotypes) == "*"] <- ""
genotypes <- data.frame(genotypes[, -1, drop = FALSE], row.names = genotypes[, 1])

colnames(genotypes) <- sub("^[^_]*_([^_]+)_(\\d+).*$", "\\1-\\2", colnames(genotypes)) #reformat the names from the weird dart format to match the pedigree file
#we need to change the names of the parents in the genotype file to match the pedigree file 
#[1] "PA10NCKY16-10"  "PA99N82-4"      "POR15NCKY022-1" "CONTROL"        "A02060-3TE"     "A06084-1TE"     "ALPINE"         "CLASSIC"        "CLEARWATER"     "HIGHLAND"       "INNOVATOR"     
#[12] "POR00LB6-1"     "POR08BD1-3"     "SUMMIT"         "TARGHEE"        "WESTERN"        "AO02183-2"     

  old = c("S_CLEARWATER.RUSSET__6_G1", "S_INNOVATOR__6_G3", "S_TARGHEE.RUSSET__6_F5","S_SUMMIT.RUSSET__6_F6","S_CLASSIC.RUSSET__6_F7", "S_HIGHLAND.RUSSET__6_F8","S_ALPINE.RUSSET__6_F12","S_WESTERN.RUSSET__6_F10","A02060-3"
          ,"A06084-1")
  new = c("CLEARWATER", "INNOVATOR", "TARGHEE","SUMMIT","CLASSIC","HIGHLAND","ALPINE","WESTERN","A02060-3TE","A06084-1TE")



idx <- match(names(genotypes), old)
names(genotypes)[!is.na(idx)] <- new[idx[!is.na(idx)]]

#make a long format df

long <- data.frame(
  `SNP Name`  = rep(rownames(genotypes), times = ncol(genotypes)),
  `Sample ID` = rep(colnames(genotypes), each = nrow(genotypes)),
  Genotype    = as.vector(as.matrix(genotypes)),
  check.names = FALSE
)


#lookat the pedigree with get_pedigree
#write.csv(ped, "pedfile.csv", row.names = FALSE)
pedfile <- "pedfile.csv"
id <- colnames(genotypes)
ped1 <- get_pedigree(id = id[1],pedfile=pedfile,na.string="NA")
nrow(ped1)

ped2 <- get_pedigree(id = id[1:2],pedfile=pedfile,na.string="NA")
nrow(ped2)

print(parentage <- pedfile[pedfile$id %in% id,])

geno.parents <- as.matrix(genotypes)
storage.mode(geno.parents) <- "numeric"

#check trio function 

str(geno.parents)

trio.ans <- check_trio(parentage=ped,geno=geno.parents,ploidy=4)
trio.ans

#why are there so many NA's in the trio?

table(ped$father %in% colnames(geno.parents))
table(ped$id %in% colnames(geno.parents))
table(ped$mother %in% colnames(geno.parents))
head(intersect(unique(ped$father), colnames(geno.parents)), 20)

sum(ped$father %in% c("", "0", "NA", NA))

#whats in ped that isnt in genotypes
ok <- ped$id     %in% colnames(geno.parents) &
  ped$mother %in% colnames(geno.parents) &
  ped$father %in% colnames(geno.parents)
bad <- ped[!ok, ]
bad$id_ok     <- bad$id     %in% colnames(geno.parents)
bad$mother_ok <- bad$mother %in% colnames(geno.parents)
bad$father_ok <- bad$father %in% colnames(geno.parents)

head(bad, 30)
table(bad$id_ok, bad$father_ok)

#explore the trio data a little
sum(trio.ans$error > 1, na.rm = TRUE)
sum(trio.ans$error < 1, na.rm = TRUE)

#looking into PCA 
geno.inverse <- Conj(t(geno.parents)) #maybe this will make it easier to assign parents for graphing
#yup, it worked 
pca_result <- prcomp(geno.inverse, center = TRUE, scale. = FALSE) #run the PCA (wow this takes a while)
xscores <- as.data.frame(pca_result$x) #make a dataframe from the PCA X-scores for plotting

rownames(xscores) <- gsub(".", "-", rownames(xscores), fixed = TRUE) #change the dots in sample name to dashes to match the pedigree file 
xscores <- xscores[rownames(xscores) != "CONTROL", ] #remove samples named "CONTROL"
ped <- ped[ped$mother != "CONTROL", ]



xscores <- xscores[rownames(xscores) %in% ped$id, ] #reduce the number of rows in xscores to the number in pedigree file to match the lingeage up later
nrow(xscores)

xscores$id <- rownames(xscores) #make a new column with the rownames (sample ids)
xscores$Group <- factor(ped$father[match(xscores$id, ped$id)]) #match the sample ids to maternal lineage from pedigree file 

ggplot(xscores, aes(x = PC1, y = PC2, color = Group)) + #plot PC1 x PC2 color coded by maternal lineage
  geom_point(size = 1.5) +
  theme_minimal() +
  labs(title = "PCA Plot", x = "PC1", y = "PC2")
